name: GitHub-Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: metrics
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics_base.svg
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 700
          plugin_languages_recent_days: 30
